FROM golang:1.22 AS build
WORKDIR /app
COPY go.mod go.sum ./
COPY . .
RUN echo 'replace github.com/staffops/otel-helper-go => /lib' >> go.mod
COPY --from=lib /lib /lib
RUN go mod tidy && CGO_ENABLED=0 go build -o /bin/go-backend .

FROM alpine:3.20
RUN apk add --no-cache ca-certificates
COPY --from=build /bin/go-backend /bin/go-backend
ENTRYPOINT ["/bin/go-backend"]
